name: causal_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - scipy=1.11.1
  - statsmodels=0.14.0
  - pip:
      - econml==0.14.1
      - dowhy==0.11
      - shap==0.42.1
      - xgboost==1.7.6
      - lightgbm==4.0.0
